# Generated by Django 3.0.3 on 2020-05-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('idbusiness', models.AutoField(primary_key=True, serialize=False)),
                ('producer_name', models.CharField(max_length=45)),
                ('is_suspendend', models.PositiveSmallIntegerField()),
                ('producer_created', models.DateTimeField(auto_now_add=True)),
                ('producer_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=45)),
                ('price_per_item', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=45)),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True, null=True)),
                ('producers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_management.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('idproduct_category', models.AutoField(primary_key=True, serialize=False)),
                ('product_category_name', models.CharField(max_length=45, unique=True)),
                ('product_category_added', models.DateTimeField(auto_now_add=True)),
                ('product_category_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('idproduct_images', models.AutoField(primary_key=True, serialize=False)),
                ('productimage_name', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='product_Images')),
                ('productimage_created', models.DateTimeField(auto_now_add=True)),
                ('productimage_updated', models.DateTimeField(auto_now=True, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimages', to='product_management.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productcategorys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcat', to='product_management.ProductCategory'),
        ),
    ]
